mysite/Bable/urls.py
# Copyright Aden Handasyde 2019
from django.conf.urls import include
from django.urls import re_path as url
from . import views
from . import models
from django.contrib import admin
from django.urls import path

# ^^^^ Use for cleaning up dodgy datatables

from rest_framework import routers
# ^^^^ Use for cleaning up dodgy datatables

# Each has a sort
# Needs a page-number
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views
app_name='Bable'
# path('admin/', admin.site.urls),
router = routers.DefaultRouter()
router.register(r'author', views.AuthorViewSet)
#router.register(r'post', views.PostViewSet)
	
# Each has a sort
# Needs a page-number
urlpatterns = [
	path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	path('i18n/', include('django.conf.urls.i18n')),
	path('examples/', views.ListCreateExampleAPIView.as_view()),
	path('posts/', views.ListCreatePostAPIView.as_view()),
	path('words/', views.ListCreateWordAPIView.as_view()),
	path('sponsor/', views.ListCreateSponsorAPIView.as_view()),
	path('angel_numbers/', views.ListCreateAngelNumberAPIView.as_view()),
	path('angel_number/<number>/', views.ShowAngelNumber, name="show_angel_number"),
	path('angel_numbered/<numbers>/', views.barcode_ai, name="barcode_ai"),
	#path('author/retrieve_by_username/<username>\w+)', views.getByUsername, name='author_username'),
	#path('docs/', include_docs_urls(title='Todo Api')),
	#path('api/v1/todo/', include("todo.urls")),

	#path('stream/', views.stream, name='stream'),
	#path('stream_unseen/', views.stream_unseen, name='stream_unseen'),
	path('api/token', obtain_auth_token, name="auth_token"),
	path('api/jwt/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/jwt/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('checkout/<int:pk>', views.CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
	path('keyup/<int:pk>/<int:post_id>', views.KeyupCheckoutSessionView.as_view(), name='keyup-checkout-session'),
	path('keyup_storefront/<int:pk>/<int:storefront_id>', views.StorefrontKeyupCheckoutSessionView.as_view(), name='storefront-keyup-checkout-session'),

	# path('admin/', admin.site.urls),
	path('logout/', views.logout_user, name='logout_user'),
	path('sign_wallet/', views.sign_wallet, name='sign_wallet'),
	path('autocomplete_votestyles/', views.autocomplete_votestyles, name='autocomplete_votestyles'),
	path('grabvoteid/', views.grabvoteid, name='grabvoteid'),
	#path('gensim_test/', views.gensim_test, name='gensim_test'),
	path('create_product_w_price/<post_id>/', views.create_product_w_price, name='create_product_w_price'),
	path('create_product_w_price/<storefront_id>/storefront/', views.create_product_w_price_storefront, name='create_product_w_price_storefront'),
	path('login/', views.login_view, name='login_view'),
	path('settings/<item>/', views.settings, name='settings'),
	path('owner/', views.owner, name='owner'),
	path('feedback/', views.feedback, name='feedback'),
	path('create_feedback/', views.create_feedback, name='create_feedback'),
	path('thanks/', views.thanks, name='thanks'),
	path('about/', views.about, name='about'),
	path('management/', views.management, name='management'),
	path('register/', views.register_view, name='register_view'),
	path('pages/', views.tower_of_bable, name='tower_of_bable'),
	path('buy_credits/coinbase/', views.home_view, name='home_view'),
	path('landingpage/', views.landingpage, name='landingpage'),
	path('landingpage/editors_choice/', views.landingpage_editors_choice, name='landingpage_editors_choice'),
	path('landingpage/features_list/', views.landingpage_features_list, name='landingpage_features_list'),
	path('landingpage/goals/', views.landingpage_goals, name='landingpage_goals'),
	path('landingpage/how_tos/', views.landingpage_how_tos, name='landingpage_how_tos'),
	path('landingpage/improvement_notes/', views.landingpage_improvement_notes, name='landingpage_improvement_notes'),
	path('landingpage/mission/', views.landingpage_mission, name='landingpage_mission'),
	path('landingpage/pitch_decks/', views.landingpage_pitch_decks, name='landingpage_pitch_decks'),
	path('landingpage/problems_solutions/', views.landingpage_problems_solutions, name='landingpage_problems_solutions'),
	path('landingpage/roadmaps/', views.landingpage_roadmaps, name='landingpage_roadmaps'),
	path('landingpage/tasks/', views.landingpage_tasks, name='landingpage_tasks'),
	path('landingpage/values/', views.landingpage_values, name='landingpage_values'),
	path('landingpage/vision/', views.landingpage_vision, name='landingpage_vision'),
	path('change_password/', views.change_password, name='change_password'),
	path('search/count/<count>/', views.search, name='search'),
	path('annotate_url/<search_url_id>/', views.annotate_url, name='annotate_url'),
	path('annotate_url_delete/<search_url_id>/', views.delete_annotation_url, name='delete_annotation_url'),
	path('annotate_url_post_comment/<search_url_id>/', views.annotate_url_post_comment, name='annotate_url_post_comment'),
	path('annotate_url_post_comment_location/<search_url_id>/<location_id>/', views.annotate_url_post_comment_location, name='annotate_url_post_comment_location'),
	path('annotate_url_comment_delete/<search_url_id>/<comment_id>/', views.annotate_url_comment_delete, name='annotate_url_comment_delete'),
	path('annotate_url_post_edits/<search_url_id>/', views.annotate_url_post_edits, name='annotate_url_post_edits'),
	path('index/count/<count>/', views.tower_of_bable_count, name='tower_of_bable_count'),
	path('spaces/', views.tob_view_spaces, name='tob_view_spaces'),
	path('spaces/count/<count>/', views.tob_view_spaces_count, name='tob_view_spaces_count'),
	path('space/<space>/count/<count>/', views.tob_space_view_count, name='tob_space_view_count'),
	path('space/<space>/', views.tob_space_view, name='tob_space_view'),
	path('space/<space_id>/post/<post_id>/count/<count>/', views.tob_spaces_post, name='tob_spaces_post'),
	path('space/<space_id>/post/<post_id>/comment/<comment_id>/', views.tob_spaces_posts_comment, name='tob_spaces_posts_comment'),
	path('users/', views.tob_view_users, name='tob_view_users'),
	path('users/count/<count>/', views.tob_view_users_count, name='tob_view_users_count'),
	path('change_dictionary/sort/<sort>/', views.change_dictionary_sort, name='change_dictionary_sort'),
	path('change_attribute/sort/<sort>/', views.change_attribute_sort, name='change_attribute_sort'),
	path('change_anon/sort/<sort>/', views.change_anon_sort, name='change_anon_sort'),
	path('change_anon_sort_char/', views.change_anon_sort_char, name='change_anon_sort_char'),
	path('change_space_sort_char/', views.change_space_sort_char, name='change_space_sort_char'),
	path('change_sponsor_sort_char/', views.change_sponsor_sort_char, name='change_sponsor_sort_char'),
	path('change_dic_sort_char/', views.change_dic_sort_char, name='change_dic_sort_char'),
	path('change_word_sort_char/', views.change_word_sort_char, name='change_word_sort_char'),
	path('change_attribute_sort_char/', views.change_attribute_sort_char, name='change_attribute_sort_char'),
	path('change_comment/sort/<sort>/', views.change_comment_sort, name='change_comment_sort'),
	path('change_word/sort/<sort>/', views.change_word_sort, name='change_word_sort'),
	path('change_post/sort/<sort>/', views.change_post_sort, name='change_post_sort'),
	path('change_post_sort_char/', views.change_post_sort_char, name='change_post_sort_char'),
	path('change_post_filter_from_date/', views.change_post_filter_from_date, name='change_post_filter_from_date'),
	path('change_post_filter_depth/', views.change_post_filter_depth, name='change_post_filter_depth'),
	path('change_storefront_sort_char/', views.change_storefront_sort_char, name='change_storefront_sort_char'),
	path('change_example/sort/<sort>/', views.change_example_sort, name='change_example_sort'),
	path('user/<user>/', views.tob_user_view, name='tob_user_view'),
	path('user/<user>/count/<count>/', views.tob_user_view_count, name='tob_user_view_count'),
	path('user/<user>/storefronts/count/<count>/', views.users_storefronts, name='users_storefronts'),
	path('create_storefront/<dictionary>/', views.create_storefront, name='create_storefront'),
	path('clickthrough_tally/', views.clickthrough_tally, name='clickthrough_tally'),
	path('user/<user>/spaces/count/<count>/', views.tob_users_spaces, name='tob_users_spaces'),
	path('user/<user>/sponsor/<sponsor>/', views.tob_users_sponsor, name='tob_users_sponsor'),
	path('user/<user>/sponsors/count/<count>/', views.tob_users_sponsors, name='tob_users_sponsors'),
	path('user/<user>/space/<space_id>/count/<count>/', views.tob_users_space, name='tob_users_space'),
	path('user/<user>/space/<space_id>/sponsor/<sponsor>/', views.tob_users_spaces_sponsor, name='tob_users_spaces_sponsor'),
	path('user/<user>/space/<space_id>/post/<post_id>/count/<count>/', views.tob_users_spaces_post, name='tob_users_spaces_post'),
	path('user/<user>/vote/<vote>/', views.tob_users_vote, name='tob_users_vote'),
	path('user/<user>/votes/count/<count>/', views.tob_users_votes, name='tob_users_votes'),
	path('user/<user>/space/<space>/post/<post>/count/<count>/', views.tob_users_spaces_post_count, name='tob_users_spaces_post_count'),
	path('user/<user>/space/<space>/post/<post>/comment/<comment>/', views.tob_users_spaces_post_comment, name='tob_users_spaces_post_comment'),
	path('user/<user>/posts/count/<count>/', views.tob_users_posts, name='tob_users_posts'),
	path('user/<user>/post/<post>/count/<count>/', views.tob_users_post, name='tob_users_post'),
	path('user/<user>/post/<post>/comment/<comment>/', views.tob_users_posts_comment, name='tob_users_posts_comment'),
	path('user/<user>/examples/count/<count>/', views.tob_users_examples, name='tob_users_examples'),
	path('user/<user>/dictionaries/count/<count>/', views.tob_users_dics, name='tob_users_dics'),

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path as url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.sitemaps.views import sitemap

from Bable.sitemaps import Static_Sitemap, Post_Sitemap, Anon_Sitemap, Dictionary_Sitemap, Word_Sitemap

from Bable.views import CancelView, SuccessView
from django.views.generic import View
from django.http.response import HttpResponse
class Adsense(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('google.com, pub-3397601491384059, DIRECT, f08c47fec0942fa0', content_type="text/plain")
sitemaps = {
    'post': Post_Sitemap(),
    'static': Static_Sitemap(),
    'user': Anon_Sitemap(),
    'dictionary': Dictionary_Sitemap(),
    'word': Word_Sitemap(),
}


urlpatterns = [
	url(r'^paypal/', include('paypal.standard.ipn.urls')),
	path('B/', include('Bable.urls')),
    path('ads.txt', Adsense.as_view()),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('', RedirectView.as_view(pattern_name='Bable:landingpage')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/Bable/templates/thanks.html
{% extends 'base.html' %}
{% load user_referencing %}
{% load vote_screen %}
{% load humanize %}
{% load mptt_tags %}
{% load static %}

{% block authenticatedposts %}
<h2>Thanks!
</h2>
{% endblock %}

{% block unauthenticatedposts %}
<h2>Thanks!
</h2>
{% endblock %}

mysite/Bable/templates/tob_users_posts.html
<!-- # Copyright Aden Handasyde 2019 -->

{% extends 'base.html' %}

{% load user_referencing %}
{% load vote_screen %}
{% load humanize %}
{% load mptt_tags %}
{% load static %}

{% block title %}
User: {{ user_anon.username.username }}'s Posts - Dream Cloud Middle Men
{% endblock %}


{% block inserts %}
<meta name="viewport" content="width=device-width">
<meta name="description" content="User: {{ user_anon.username.username }}'s Posts - Dream Cloud Middle Men">
<meta property="og:image" content="{% static 'babylonpolice.jpg' %}">
{% endblock %}

{% block authenticatedposts %}
<div class=usersusername>
	<h2>
	<a href="{% url 'Bable:tob_user_view_count' user_anon.username.username 0 %}">User: {{ user_anon.username.username }}</a>
	</h2>
</div>
<div class=usersposts>
	<div class=sectiontitle>
		<a href="{% url 'Bable:tob_users_posts' user_anon.username.username 0 %}"><h3>
			Posts:
		</h3></a>
	</div>
	<div class=possectionsort>
		<form name=post_sort action="{% url 'Bable:change_post_sort_char' %}" method=post>
			{% csrf_token %}
			{{ post_sort_form }}
		</form>
		<script>
			var form = document.querySelector('form[name="post_sort"]');
			form.addEventListener('change', function() {
			    form.submit();
			});
		</script>
	</div>
	<div class=posts>
		{% if users_posts.count %}
			{% for post in users_posts.all %}
			<div class=post>
				<div class=posttop>
					<div class=postpreview>
						{% if post.url2 %}
							<a href="{{ post.url2 }}"><img src="{% static 'babylonpolice.com.gif' %}" style="height: 6em; width: 6em;"></a>
						{% else %}
							<img src="{% static 'babylonpolice.com.gif' %}" style="height: 6em; width: 6em;">
						{% endif %}
					</div>
					<div class=posttitle>
						{% if not post.author.username %}
						<a href="{% url 'Bable:tob_post' post.id %}"><h4>{{ post.title }}</h4></a>
						{% else %}
						<a href="{% url 'Bable:tob_users_post' post.author.username post.id 0 %}"><h4>{{ post.title }}</h4></a>
						{% endif %}
					</div>
					{% if post.author.username == user_anon.username.username %}
					<div class=postdel>
						<a href="{% url 'Bable:delete_own_post' post.author.username post.id %}">X</a>
					</div>
					{% endif %}
				</div>
				<div class=postbody>
					{{ post.body|usernames|spaces|urlize|truncatechars:144 }}
				</div>
				<div class=postwords>
					Words:
					{% for word in post.words.all %}
					<a href="{% url 'Bable:tob_users_dic_word_count' post.author.username word.home_dictionary.the_dictionary_itself word.the_word_itself 0 %}">
						{{ word.the_word_itself }}
					</a>
					{% endfor %}
				</div>
				<div class=postvotes>
					Votes:
					{% for vote in post.votes.all %}
					<a href="{% url 'Bable:vote' vote.id %}">{{ vote.votes }}</a>: <a href="{% url 'Bable:tob_users_space' vote.author.username vote.the_vote_style.to_full.id 0 %}">{{ vote.the_vote_style.the_word_itself }}</a>
					{% endfor %}
				</div>
				<div class=postviews>
					Views: {{ post.viewcount }}
				</div>
				<div class=postlatest>
					Latest: {{ post.latest_change_date }}
				</div>
				{% if not post.author.username %}
				<div class=postauthor>
					/u/anonymous
				</div>
				{% else %}
				<div class=postauthor>
					<a href="{% url 'Bable:tob_user_view_count' post.author.username 0 %}">/u/{{ post.author.username }}</a>
				</div>
				{% endif %}
			</div>
			{% endfor %}
		{% else %}
			<div class=post>
				This user has not marked their post.
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block unauthenticated_posts %}
<div class=usersusername>
	<h2>
	<a href="{% url 'Bable:tob_user_view_count' user_anon.username.username 0 %}">User: {{ user_anon.username.username }}</a>
	</h2>
</div>
<div class=usersposts>
		<div class=sectiontitle>
			<a href="{% url 'Bable:tob_users_posts' user_anon.username.username 0 %}"><h3>
				Posts:
			</h3></a>
		</div>
		<div class=possectionsort>
			<div id=possortnav>
				Sort: {{ loggedinanon.get_post_sort_display }}
			</div>
			<div class=dropdown-content-pos-sort>
				<div class=popular>
					<div class=viral>
						<a href="{% url 'Bable:change_post_sort' 'viral' %}">Viral</a>
					</div>
					<div class=early>
						<a href="{% url 'Bable:change_post_sort' 'early' %}">Early</a>
					</div>
					<div class=freshest>
						<a href="{% url 'Bable:change_post_sort' 'freshest' %}">Freshest</a>
					</div>
					<div class=eldest>
						<a href="{% url 'Bable:change_post_sort' 'eldest' %}">Eldest</a>
					</div>
					<div class=uniques>
						<a href="{% url 'Bable:change_post_sort' 'uniques' %}">Uniques</a>
					</div>
					<div class=voters>
						<a href="{% url 'Bable:change_post_sort' 'voters' %}">Voters</a>
					</div>
				</div>
				<div class=stats>
					<div class=broadness>
						<a href="{% url 'Bable:change_post_sort' 'broadness' %}">Broadness</a>
					</div>
					<div class=intricacy>
						<a href="{% url 'Bable:change_post_sort' 'intricacy' %}">Intricacy</a>
					</div>
					<div class=talkative>
						<a href="{% url 'Bable:change_post_sort' 'talkative' %}">Talkative</a>
					</div>
					<div class=homes>
						<a href="{% url 'Bable:change_post_sort' 'homes' %}">Homes</a>
					</div>
					<div class=encouraged>
						<a href="{% url 'Bable:change_post_sort' 'encouraged' %}">Encouraged</a>
					</div>
					<div class=votes>
						<a href="{% url 'Bable:change_post_sort' 'votes' %}">Votes</a>
					</div>
				</div>
			</div>
		</div>
		<div class=posts>
			{% if users_posts.count %}
				{% for post in users_posts.all %}
				<div class=post>
					<div class=posttop>
						<div class=postpreview>
							{% if post.url2 %}
								<a href="{{ post.url2 }}"><img src="{% static 'growadic.png' %}" style="height: 6em; width: 6em;"></a>
							{% else %}
								<img src="{% static 'babylonpolice.com.gif' %}" style="height: 6em; width: 6em;">
							{% endif %}
						</div>
						<div class=posttitle>
							{% if not post.author.username %}
						<a href="{% url 'Bable:tob_post' post.id %}"><h4>{{ post.title }}</h4></a>
						{% else %}
						<a href="{% url 'Bable:tob_users_post' post.author.username post.id 0 %}"><h4>{{ post.title }}</h4></a>
						{% endif %}
						</div>
					</div>
					<div class=postbody>
						{{ post.body|usernames|spaces|urlize|truncatechars:144 }}
					</div>
					<div class=postwords>
						Words:
						{% for word in post.words.all %}
						<a href="{% url 'Bable:tob_users_dic_word_count' post.author.username word.home_dictionary.the_dictionary_itself word.the_word_itself 0 %}">
							{{ word.the_word_itself }}
						</a>
						{% endfor %}
					</div>
					<div class=postvotes>
						Votes:
						{% for vote in post.votes.all %}
						<a href="{% url 'Bable:vote' vote.id %}">{{ vote.votes }}</a>: <a href="{% url 'Bable:tob_users_space' vote.author.username vote.the_vote_style.to_full.id 0 %}">{{ vote.the_vote_style.the_word_itself }}</a>
						{% endfor %}
					</div>
					<div class=postviews>
						Views: {{ post.viewcount }}
					</div>
					<div class=postlatest>
						Latest: {{ post.latest_change_date }}
					</div>
					{% if not post.author.username %}
					<div class=postauthor>
						/u/anonymous
					</div>
					{% else %}
					<div class=postauthor>
						<a href="{% url 'Bable:tob_user_view_count' post.author.username 0 %}">/u/{{ post.author.username }}</a>
					</div>
					{% endif %}
				</div>
				{% endfor %}
			{% else %}
				<div class=post>
					This user has not marked their post.
				</div>
			{% endif %}
		</div>
	</div>

{% endblock %}

mysite/Bable/templates/users_storefronts.html
{% extends 'base.html' %}
{% load user_referencing %}
{% load vote_screen %}
{% load humanize %}
{% load mptt_tags %}
{% load static %}
{% load i18n %}

{% block title %}
Users Storefronts - {{ request.META.HTTP_HOST|stripwww }}
{% endblock %}


{% block inserts %}
<meta name="viewport" content="width=device-width">
<meta property="og:description" content="{{ users_post.title }} - Babylon Police">
<meta property="og:image" content="{% static 'babylonpolice.jpg' %}">
{% endblock %}






{% block authenticatedposts %}
<div class=storefronts style="margin-top:50px;">
	<div class=storefronts-heading>
		Storefronts ({{storefronts_count}}):
	</div>
	<div class=spasectionsort>
		<form name=space_sort action="{% url 'Bable:change_storefront_sort_char' %}" method=post>
			{% csrf_token %}
			{{ storefront_sort_form }}
		</form>
		<script>
			var form = document.querySelector('form[name="storefront_sort"]');
			form.addEventListener('change', function() {
			    form.submit();
			});
		</script>
	</div>
	<div>
	{% for storefront in storefronts %}
	<div class=storefront>
		<div>
			Logo: <a href="{% url 'Bable:tob_word' storefront.logo.id %}">{{ storefront.logo.the_word_itself }}</a>
		</div>
		<div>
			Title: <a href="{% url 'Bable:tob_storefront' storefront.id %}">{{ storefront.title }}</a>
		</div>
		<div>
			Preview Text: {{ storefront.preview_text }}
		</div>
		<div>
			Products Count: {{ storefront.products_count }}
		</div>
		<div>
			Sales Count: {{ storefront.sales_count }}
		</div>
		<div>
			Business Admins: 
			{% for admin in storefront.business_admin.all %}
			<a href="{% url 'Bable:tob_user_view' admin.username %}">/u/{{ admin.username }}</a>&nbsp;
			{% endfor %}
		</div>
		<div>
			Views: {{ storefront.views }}
		</div>
		<div>
			Total Product Value: {{ storefront.total_product_value }}
		</div>
		<div>
			Total Sales Volume: {{ storefront.total_sales_made }}
		</div>
		
		
		<div>
			Disclaimer: {{ storefront.disclaimer }}
		</div>
	</div>
	{% endfor %}
	</div>
	<div class=spasectionsort>
		<form name=storefron_dic action="{% url 'Bable:users_storefronts' user_anon.username.username 0 %}" method=post>
			{% csrf_token %}
			{{ storefront_dic_form }}
		</form>
		<script>
			var form = document.querySelector('form[name="storefront_dic"]');
			form.addEventListener('change', function() {
			    form.submit();
			});
		</script>
	</div>
	<form name=space_sort action="{% url 'Bable:create_storefront' storefront_dic %}" method=post>
		{% csrf_token %}
		{{ storefront_form }}
		<button type=submit>Submit</button>
	</form>
</div>
{% endblock %}

{% block unauthenticated_posts %}

{% endblock %}

{% block scripts %}
<script>
	function openComment(starter) {
			var element = document.getElementById(starter + "form");
			if (element.style.display === "inline-block") {
				element.style.display = "none";
			} else {
				element.style.display = "inline-block";
			}
		}

	function openCommentThread(starter, com) {
		var element = document.getElementById(starter).getElementById(com);
		if (element.style.display === "inline-block") {
			element.style.display = "none";
		} else {
			element.style.display = "inline-block";
		}
	}

	function comCollapse(node) {
		var element = document.getElementById(node)
		if (element.style.display === "inline-block") {
			element.style.display = "none";
		} else {
			element.style.display = "inline-block";
		}
	}
</script>
{% endblock %}